# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.perm.protos.Actor" do
    optional :id, :string, 1
    optional :issuer, :string, 2
  end
end

module CloudFoundry
  module Perm
    module Protos
      Actor = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.Actor").msgclass
    end
  end
end
