# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: context.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.perm.protos.Context" do
    map :context, :string, :string, 1
  end
end

module CloudFoundry
  module Perm
    module Protos
      Context = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.Context").msgclass
    end
  end
end
