# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.perm.protos.Group" do
    optional :id, :string, 2
  end
end

module CloudFoundry
  module Perm
    module Protos
      Group = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.Group").msgclass
    end
  end
end
