# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: permission.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.perm.protos.Permission" do
    optional :action, :string, 2
    optional :resource_pattern, :string, 3
  end
end

module CloudFoundry
  module Perm
    module Protos
      Permission = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.Permission").msgclass
    end
  end
end
