# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: permission_service.proto for package 'cloud_foundry.perm.protos'

require 'grpc'
require 'permission_service_pb'

module CloudFoundry
  module Perm
    module Protos
      module PermissionService
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'cloud_foundry.perm.protos.PermissionService'

          rpc :HasPermission, HasPermissionRequest, HasPermissionResponse
          rpc :ListResourcePatterns, ListResourcePatternsRequest, ListResourcePatternsResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
