# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto

require 'google/protobuf'

require 'context_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.perm.protos.AssignRoleRequest" do
    optional :actor, :string, 1
    optional :role, :string, 2
    optional :context, :message, 3, "cloud_foundry.perm.protos.Context"
  end
  add_message "cloud_foundry.perm.protos.AssignRoleResponse" do
  end
  add_message "cloud_foundry.perm.protos.HasRoleRequest" do
    optional :actor, :string, 1
    optional :role, :string, 2
    optional :context, :message, 3, "cloud_foundry.perm.protos.Context"
  end
  add_message "cloud_foundry.perm.protos.HasRoleResponse" do
    optional :hasRole, :bool, 1
  end
end

module CloudFoundry
  module Perm
    module Protos
      AssignRoleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.AssignRoleRequest").msgclass
      AssignRoleResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.AssignRoleResponse").msgclass
      HasRoleRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.HasRoleRequest").msgclass
      HasRoleResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.HasRoleResponse").msgclass
    end
  end
end
