# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: role.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cloud_foundry.perm.protos.Role" do
    optional :name, :string, 2
  end
end

module CloudFoundry
  module Perm
    module Protos
      Role = Google::Protobuf::DescriptorPool.generated_pool.lookup("cloud_foundry.perm.protos.Role").msgclass
    end
  end
end
